name: tropical_ship_supply
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  cherry_toast: ^1.11.0
  pluto_grid: ^8.0.0
  csv: ^6.0.0
  file_picker: ^8.0.6
  path_provider: ^2.1.3
  html: ^0.15.4
  http_parser: ^4.0.0
  shared_preferences: ^2.3.2
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/